In [ ]:
import torch

x = torch.rand(3)
print(x)

tensor([0.0173, 0.4004, 0.5728])


In [ ]:
import torch
# https://pytorch.org/docs/stable/generated/torch.Tensor.requires_grad.html   # (requires_grad = True)    Documentation

x = torch.rand(3, requires_grad=True)
print(x)

tensor([0.6209, 0.4702, 0.2588], requires_grad=True)


In [ ]:
y = x+2  # Y has an attribute grad_fn which point to Gradient function , function is Add_Backword which will calculate the Gradient of y  w.r.t x
print(y)

# Calculates the computational Graph by PyTorch
# Pytorch automatically create a Function for us
# This function used in the BackPropagation to get the Gradient


tensor([2.6209, 2.4702, 2.2588], grad_fn=<AddBackward0>)


In [ ]:
z  = y*y*2
z = z.mean()

print(z)

tensor(12.0488, grad_fn=<MeanBackward0>)


In [ ]:
# https://pytorch.org/docs/stable/generated/torch.Tensor.backward.html

z.backward()   #dz/dx  # Calcualtes the Gradient
print(x.grad)


tensor([3.4945, 3.2936, 3.0117])


In [ ]:
# When we Dont Specify the Argument

x = torch.rand(3, requires_grad=False)     # requires_grad = False
print(x)

y = x+2
print(y)

z  = y*y*2
z = z.mean()

print(z)

# z.backward()   #dz/dx  # Calcualtes the Gradient
# print(x.grad)

tensor([0.2060, 0.0339, 0.9101])
tensor([2.2060, 2.0339, 2.9101])
tensor(11.6481)


In [ ]:
# Produces Error z.backward()

x = torch.rand(3, requires_grad=False)
print(x)

y = x+2
print(y)

z  = y*y*2
z = z.mean()

print(z)

z.backward()   #dz/dx  # Calcualtes the Gradient
# print(x.grad)

tensor([9.4147e-01, 7.7683e-04, 1.1425e-01])
tensor([2.9415, 2.0008, 2.1142])
tensor(11.4169)


RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [ ]:
# Jacobian Matrix
# J.v = Jacobian matrix with partial Derivative  * Gradient Vector = Final Gradient

# https://machinelearningmastery.com/a-gentle-introduction-to-the-jacobian/  # Docuemtation

# The Jacobian matrix collects all first-order partial derivatives of a multivariate function that can be used for backpropagation.
# The Jacobian determinant is useful in changing between variables, where it acts as a scaling factor between one coordinate space and another

# Chain Rule

In [ ]:
# Ignoring Mean Operation

x = torch.rand(3, requires_grad=True)
print(x)

y = x+2
print(y)

z  = y*y*2
#z = z.mean()

print(z)

# z.backward()
# print(x.grad)

tensor([0.3277, 0.4392, 0.1337], requires_grad=True)
tensor([2.3277, 2.4392, 2.1337], grad_fn=<AddBackward0>)
tensor([10.8367, 11.8992,  9.1056], grad_fn=<MulBackward0>)


In [ ]:
# Ignoring Mean Operation and Backword On the Produces Error

x = torch.rand(3, requires_grad=True)
print(x)

y = x+2
print(y)

z  = y*y*2
#z = z.mean()

print(z)

z.backward()
# print(x.grad)

tensor([0.4959, 0.8067, 0.5198], requires_grad=True)
tensor([2.4959, 2.8067, 2.5198], grad_fn=<AddBackward0>)
tensor([12.4588, 15.7547, 12.6983], grad_fn=<MulBackward0>)


RuntimeError: grad can be implicitly created only for scalar outputs

In [ ]:
# Ignoring Mean Operation means Scaler value and adding vector

x = torch.rand(3, requires_grad=True)
print(x)

y = x+2
print(y)

z  = y*y*2
#z = z.mean()

print(z)

v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)
z.backward(v)

print(x.grad)

tensor([0.8268, 0.7506, 0.5405], requires_grad=True)
tensor([2.8268, 2.7506, 2.5405], grad_fn=<AddBackward0>)
tensor([15.9815, 15.1319, 12.9080], grad_fn=<MulBackward0>)
tensor([1.1307e+00, 1.1002e+01, 1.0162e-02])


In [ ]:
# PyTorch Prevent the tracking the History from the computation Graph & also stops the creating the gradient fucntion

x = torch.rand(3, requires_grad=True)
print(x)

# x.requires_grad_(False)
# x.detach()
# with torch.no_grad():

tensor([0.9421, 0.9525, 0.5449], requires_grad=True)


In [ ]:
x = torch.rand(3, requires_grad=True)
print(x)

x.requires_grad_(False)     # Modiified The Variable (Inplace Operation)
print(x)

tensor([0.4204, 0.8054, 0.1919], requires_grad=True)
tensor([0.4204, 0.8054, 0.1919])


In [ ]:
x = torch.rand(3, requires_grad=True)
print(x)

y = x.detach()
print(y)

tensor([0.5876, 0.1002, 0.6165], requires_grad=True)
tensor([0.5876, 0.1002, 0.6165])


In [ ]:
x = torch.rand(3, requires_grad=True)
print(x)

with torch.no_grad():
   y = x + 2
   print(y)

tensor([0.7551, 0.0907, 0.1614], requires_grad=True)
tensor([2.7551, 2.0907, 2.1614])


In [ ]:
# Training Example

import torch
weights = torch.ones(4, requires_grad=True)

for epoch in range(1):   # 1 Iteration
     model_output = (weights * 3).sum()
     model_output.backward()
     print(weights.grad)

tensor([3., 3., 3., 3.])


In [ ]:
# Training Example

import torch
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):     # 3 Iterations
     model_output = (weights * 3).sum()
     model_output.backward()
     print(weights.grad)

# We got incorrect Gradients

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


In [ ]:
# Training Example

import torch
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):     # 3 Iterations
     model_output = (weights * 3).sum()
     model_output.backward()
     print(weights.grad)
     weights.grad.zero_()   # Inplace operation

# Now We have got correct Gradients

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [ ]:
# Optimization (No Run Please)

# https://stackoverflow.com/questions/53975717/pytorch-connection-between-loss-backward-and-optimizer-step    # Step function Documentation


weights = torch.ones(4, requires_grad=True)

optimizer = torch.optim.SGD(weights, lr=0.01)

# After computing the gradients for all tensors in the model, calling optimizer.step() makes the optimizer iterate over all parameters (tensors) it is supposed to update and use their internally stored grad to update their values.
optimizer.step()
optimizer.zero_grad()


In [ ]:
# ( No Run Please )

weights = torch.ones(4, requires_grad=True)

z.backward()
weights.grad.zero_()   # Inplace operation
