In [ ]:
import torch

In [ ]:
# https://pytorch.org/docs/stable/generated/torch.empty.html      # Empty Documentation

x = torch.empty(1)
print(x)

tensor([0.0001])


In [ ]:
x1 = torch.empty(3)
print(x1)

tensor([3.8112e-20, 3.0955e-41, 3.8107e-20])


In [ ]:
x2 = torch.empty(2,3)
print(x2)

tensor([[3.7248e-20, 3.0955e-41, 3.6059e-20],
        [3.0955e-41, 0.0000e+00, 0.0000e+00]])


In [ ]:
x3 = torch.empty(2, 2,3)
print(x3)

tensor([[[5.4928e-05, 1.0254e-11, 2.1670e-04],
         [8.5410e+20, 6.6756e+22, 3.1984e+21]],

        [[2.6076e-09, 6.4174e-10, 2.4829e-18],
         [3.1360e+27, 7.0800e+31, 3.1095e-18]]])


In [ ]:
x = torch.rand(2,2)
print(x)

tensor([[0.7335, 0.7631],
        [0.9470, 0.2128]])


In [ ]:
x = torch.zeros(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
x = torch.ones(2,4)
print(x.dtype)

torch.float32


In [ ]:
x = torch.ones(2,4, dtype=torch.int)
print(x.dtype)

torch.int32


In [ ]:
x = torch.ones(2,4, dtype=torch.double)
print(x.dtype)

torch.float64


In [ ]:
x = torch.ones(2,4, dtype=torch.float16)
print(x.dtype)

torch.float16


In [ ]:
x = torch.ones(2,4, dtype=torch.float16)
print(x.size())

torch.Size([2, 4])


In [ ]:
x = torch.tensor([2.5, 0.1])
print(x)

tensor([2.5000, 0.1000])


In [ ]:
x = torch.rand(2,2)
y = torch.rand(2,2)

print(y)
y.add_(x)
print(y)

# An in-place operation is an operation that changes directly the content of a given Tensor without making a copy.
# Inplace operations in pytorch are always postfixed with a _, like .add_() or .scatter_().
# Python operations like += or *= are also inplace operations

tensor([[0.1180, 0.6637],
        [0.2268, 0.4963]])
tensor([[0.4895, 1.5355],
        [0.7541, 0.8202]])


In [ ]:
x = torch.rand(2,2)
y = torch.rand(2,2)

print(y)
y.add(x)
print(y)

tensor([[0.5776, 0.9542],
        [0.1353, 0.8210]])
tensor([[0.5776, 0.9542],
        [0.1353, 0.8210]])


In [ ]:
x = torch.rand(2,2)
y = torch.rand(2,2)

print(y)
y.mul_(x)
print(y)

# An in-place operation is an operation that changes directly the content of a given Tensor without making a copy.
# Inplace operations in pytorch are always postfixed with a _, like .add_() or .scatter_().
# Python operations like += or *= are also inplace operations

tensor([[0.8884, 0.5123],
        [0.9230, 0.3415]])
tensor([[0.7241, 0.2958],
        [0.0575, 0.1973]])


In [ ]:
# item() method

x = torch.rand(2,3)
print(x)
print(x[1,1].item())

tensor([[0.4001, 0.0604, 0.6763],
        [0.2057, 0.4886, 0.9706]])
0.4885726571083069


In [ ]:
# View Method (changes the shape of the tensors)

x = torch.rand(4,4)
print(x)
y = x.view(16)
print(y)

tensor([[0.1086, 0.1764, 0.3171, 0.0112],
        [0.6028, 0.4976, 0.6751, 0.9318],
        [0.2670, 0.2212, 0.8749, 0.2185],
        [0.4194, 0.8592, 0.3915, 0.8117]])
tensor([0.1086, 0.1764, 0.3171, 0.0112, 0.6028, 0.4976, 0.6751, 0.9318, 0.2670,
        0.2212, 0.8749, 0.2185, 0.4194, 0.8592, 0.3915, 0.8117])


In [ ]:
# View Method (changes the shape of the tensors)

x = torch.rand(4,4)
print(x)
y = x.view(8,2)
print(y)

tensor([[0.6482, 0.6212, 0.4623, 0.9616],
        [0.8897, 0.3406, 0.9035, 0.6745],
        [0.8285, 0.5102, 0.2383, 0.8298],
        [0.0328, 0.2572, 0.7392, 0.1758]])
tensor([[0.6482, 0.6212],
        [0.4623, 0.9616],
        [0.8897, 0.3406],
        [0.9035, 0.6745],
        [0.8285, 0.5102],
        [0.2383, 0.8298],
        [0.0328, 0.2572],
        [0.7392, 0.1758]])


In [ ]:
# View Method (changes the shape of the tensors)

x = torch.rand(4,4)
print(x)
y = x.view(-1,8)
print(y)
print(y.size())

tensor([[0.4653, 0.4950, 0.8361, 0.6175],
        [0.4689, 0.0973, 0.1697, 0.6375],
        [0.2712, 0.2196, 0.4445, 0.9650],
        [0.5693, 0.6267, 0.9435, 0.5829]])
tensor([[0.4653, 0.4950, 0.8361, 0.6175, 0.4689, 0.0973, 0.1697, 0.6375],
        [0.2712, 0.2196, 0.4445, 0.9650, 0.5693, 0.6267, 0.9435, 0.5829]])
torch.Size([2, 8])


In [ ]:
# Converting Torch_Tensor to Numpy
import numpy as np

a = torch.ones(5)
print(a)
b = a.numpy()
print(type(b))

tensor([1., 1., 1., 1., 1.])
<class 'numpy.ndarray'>


In [ ]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(type(b))

# If Tensors are on CPU & not the GPU then both objects shares the same memory Location.
# This means if we change one then it reflects on other

a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [ ]:
# Converting Numpy to Torch_Tensor

# https://pytorch.org/docs/stable/generated/torch.from_numpy.html      # from _numpy method documentation

a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

# If this is happen only when Tensors are on GPU
# This means if we change one then it reflects on other

a +=1

print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [ ]:
# Cuda

if torch.cuda.is_available():
   device = torch.device("cuda")
   x = torch.ones(5, device=device)
   y = torch.ones(5)
   y = y.to(device)
   z = x + y
   z = z.to("cpu")

In [ ]:
x = torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
